### ISSUE TITLE
M2 air touchpad dwt not working

### ISSUE THREAD

**Issue by cyrinux** [AsahiLinux/linux#103]
Hi,

I would like to report properly an issue regarding touchpad, I understand some other people complains about this on IRC.

The disable while typing feature / "dwt", even if activate, looks to be not working on at least macbook M2 air.

I know for some people with macbook M1 pro it works.

Here an extract from `libinput list-devices` for both models.

Macbook M1 pro touchpad:

``` 
Device:           Apple Internal Keyboard / Trackpad
Kernel:           /dev/input/event1
Group:            2
Seat:             seat0, default
Size:             131x82mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    enabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge
Click methods:    button-areas *clickfinger
Disable-w-typing: enabled
Disable-w-trackpointing: enabled
Accel profiles:   flat *adaptive
Rotation:         n/a
 ```

Macbook M2 air touchpad:

```
Device:           Apple MTP multi-touch
Kernel:           /dev/input/event3
Group:            2
Seat:             seat0, default
Size:             131x82mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    enabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge
Click methods:    button-areas *clickfinger
Disable-w-typing: enabled
Disable-w-trackpointing: enabled
Accel profiles:   flat *adaptive
Rotation:         n/a
```

Any idea about this issue ? Is it a kernel or a libinput profile missconfig ?

I can give more informations if needed. Its very disturbing when you type with thumb on this big touchpad 😆

**Comment by tramtrist** [comment]
I am having the exact same issue.  Also curious if this is a configuration or lower level issue.

**Comment by marcan** [comment]
This is a userspace issue, the kernel driver doesn't know anything about dwt.

I know what's going on. We expose the internal M2 trackpad/keyboard as "HOST" bus devices. This needs a quirk added [here](https://gitlab.freedesktop.org/libinput/libinput/-/blob/main/quirks/50-system-apple.quirks#L30) to match on that and mark it as an internal keyboard, which will enable dwt. The match part should probably mirror the touchpad match [here](https://gitlab.freedesktop.org/libinput/libinput/-/blob/main/quirks/50-system-apple.quirks#L108), so matching on `Apple*MTP*` and the vendor ID and keyboard type.

If you're up for it, that's an easy patch to submit directly to libinput. Otherwise I can do it later :)

**Comment by cyrinux** [comment]
Thanks marcan, I will try!

**Comment by cyrinux** [comment]
@marcan if you want to review here https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/853
I finally got my expected behavior back thanks, mouse cursor don't move at all anymore while I am typing.

**Comment by cyrinux** [comment]
It's merge 🙂
