### ISSUE TITLE
MacOS Shutting down randomly and rebooting to AsahiLinux

### ISSUE THREAD

**Issue by LunarScout118** [AsahiLinux/linux#170]
**Device**: 13-Inch M2 MacBook Pro 2022
**MacOS Version**: Ventura 13.5

**Steps to reproduce**: Simply wait and there is a chance your MacBook may reboot into linux for no reason, Don't touch the computer or do anything, just wait.

**Severity**: _Minor_* 
This issue can be annoying but is usually rare, usually happening once every week or two.

**Comment by marcan** [comment]
Is macOS set as the default boot OS? If not, then any reboot would go into Linux (which could happen e.g. due to a macOS crash/panic). You can change the default boot OS by holding down Option while selecting the OS in the boot picker, or by using Startup Disk in the macOS settings.

In any case all of the boot selection scaffolding stuff is entirely Apple code, so if Linux is booting there's nothing we can do about it at that point. Our code isn't involved in OS selection at all, that's all in iBoot. If you're seeing Linux boot when macOS is the default boot OS, that's a really weird bug and you should report it to Apple.
