### ISSUE TITLE
TSO Support and execve

### ISSUE THREAD

**Issue by wrenger** [AsahiLinux/linux#189]
In 6.3 @marcan added rudimentary TSO support over `prctl` (https://github.com/AsahiLinux/linux/commit/b5c05cbffb0488c7618106926d522cc3b43d93d5). This toggles the memory model for the currently running process. A caveat of the current implementation is that this does not survive `execve`. Is this the expected behavior or a bug?

Context: I would like to run some unmodified executables with TSO enabled and the `prctl+execve` way would be perfect for this. Unfortunately, I do not know any other way to enable TSO for this. Especially as the kernel modules ([cyyself/m1tso-linux](https://github.com/cyyself/m1tso-linux), [leeehui/tso-enabler](https://github.com/leeehui/tso-enabler)) that enabled this system-wide are not working anymore.

**Comment by wrenger** [comment]
Here, it is disabled after exec:

https://github.com/AsahiLinux/linux/blob/b5c05cbffb0488c7618106926d522cc3b43d93d5/arch/arm64/kernel/process.c#L715-L717

**Comment by marcan** [comment]
This is intentional, TSO support should only be used by emulators and they need to be able to exec native binaries without the TSO flag carrying over. There are no plans to allow `prctl+execve` to turn on TSO for arbitrary binaries, that is considered an anti-pattern. There are no legitimate reasons to run native arm64 software with TSO; if the software breaks without TSO, it is broken and noncompliant with the architecture and should be fixed.

If you need to do this for some experimental / benchmark reason (e.g. trying native apps with TSO just to see what the perf loss is), then you can just use something like LD_PRELOAD to inject the prctl to enable TSO again.
