### ISSUE TITLE
Issue with OpenGL applications crashing when using Hyprland 0.42.0

### ISSUE THREAD

**Issue by Moerliy** [AsahiLinux/linux#318]
This is an issue that came up in the Hyprland repo ([ref](https://github.com/hyprwm/Hyprland/issues/7364)).

> The recent release of Hyprland 0.42.0 introduced significant changes, with the most notable being the switch from wlroots to aquamarine.
> However, this update has caused issues on Asahi Linux, where applications that use OpenGL, such as Firefox, Kitty,  wpaperd or Chromium …, are no longer running properly. 

It seems that a bunch of people are running into this and Hyprland's lead developer [vaxerski](https://github.com/vaxerski) seems to be out of options on how to solve or approach this bug. 

[marcan](https://github.com/marcan) has [commented](https://github.com/hyprwm/Hyprland/issues/7161#issuecomment-2282702058) on this a couple of days ago:

> If you are trying to create linear buffers with arbitrary pitch, that won't work. The hardware only supports 16-byte aligned pitch. This is your bug, not a driver bug. You need to use buffer formats that are supported by the hardware.

and [vaxerski](https://github.com/vaxerski) thinks the bug has to do something with Asahi:

> I am no marcan, I don't use or understand Apple hardware, but I fail to see where I went wrong as I feel like I report formats correctly. I mean, AMD, Intel, Nvidia work.
>The comment about 16-bit aligned linear buffers, sure, but it's not hyprland that reports these things. For mesa drm, we only report formats, that's it.
>Currently we report formats that EGL reports as renderable, with the patch we report formats that the KMS primary plane supports.
>I feel like I am out of options?

I'm not sure if the bug originates in Hyprland or the Asahi kernel but I would love for this to get resolved so I thought some people here who have a bit more knowledge about this, could help with the investigation of the problem.

Edit: I was a bit at a loss on where to post this issue, so I hope it isn't completely out of place.

**Comment by marcan** [comment]
This is pretty unlikely to be our bug, since all other compositors have no issue here, and it's definitely not a kernel bug since if anything Hyprland interacts with Mesa.

The Hyprland authors say it "works on intel, AMD, nvidia". Those are all non-kmsro systems. Almost all *other* systems use kmsro and split display/render. I bet hyprland is equally broken on Rockchip, Mali, Qualcomm, etc.

Re the original pitch issue, I took a quick look at the hyprland code and immediately saw at least one place where pitch == width * 4 is assumed, which is an incorrect assumption to make. So their code is very clearly broken and has never been tested on a system with pitch alignment requirements. They need to debug this, not us.

I would suggest the Hyprland author interact with the Mesa/freedesktop community to learn how to write a compositor correctly using APIs and flows that work actoss different hardwares and respect hardware limitations and works with kmsro... but they are banned from that community, for very good reasons. So now they're on their own. Good luck.
