### ISSUE TITLE
Would it be possible to set a custom notch height?

### ISSUE THREAD

**Issue by danberindei** [AsahiLinux/linux#341]
Gnome/Mutter only allow fractional scaling if the resulting width and height are integers.

https://github.com/GNOME/mutter/blob/main/src/backends/meta-monitor.c#L1998

If I set `apple_dcp.show_notch=1` on my M1, the display height is 2234 = 2 * 1117, and 200% is the only scaling factor with an integer result.

If I could set `apple_dcp.show_notch=2`  to make apple_dcp override the hardware `notch-height` and make it 2 pixels high, then Mutter would see a display height of 2232, and it would allow me to set the scaling factor to 225% when I have an external monitor and 175% when I'm only using the laptop monitor.

Would this work? Are there any technical/philosophical reasons why it shouldn't be done?

**Comment by marcan** [comment]
This is a problem with Mutter and should be fixed in Mutter. It's not the kernel's job to provide workarounds for buggy compositors. There is a lot more work that needs to go into desktop environments to properly support notches anyway.

The compositor could *trivially* round down the effective resolution like this itself to provide more options if it absolutely requires the integer ratios, so it makes absolutely no sense to have this in the kernel.

**Comment by danberindei** [comment]
Thanks for the response @marcan, I'm going to raise an issue with Mutter. 

One question: is information about the notch exposed somewhere (ideally not Asahi-specific), so Mutter can decide whether it's best to blank the first 2 lines from the top or the first 2 lines from the bottom?

PS: I'm sure the notch support in Gnome/Mutter could go much further, but the [Date Menu Formatter](https://extensions.gnome.org/extension/4655/date-menu-formatter/) extension lets me widen the date + clock so that they are not drawn over the notch, and that pretty much covers everything I need.

PPS: I found [a Mutter patch](https://github.com/KZDKM/Asahi-GNOME/blob/main/mutter/MBP14_notch.patch) that does what I need, but while it is trivial, it doesn't look like something that the Gnome team would ever accept in their codebase.
