### ISSUE TITLE
vkmark segfaults on launch if CONFIG_DRM_ASAHI=y

### ISSUE THREAD

**Issue by zzywysm** [AsahiLinux/linux#349]
On NixOS, if I attempt to run the Vulkan benchmark `vkmark`, it only runs if the GPU driver is built as a module.  If I change `CONFIG_DRM_ASAHI=y` instead of `=m`, vkmark segfaults on launch.  The stacktrace from journalctl:

```
Dec 18 22:05:02 greenrosetta systemd-coredump[23456]: [🡕] Process 23454 (vkmark) of user 1000 dumped core.
    Module libexpat.so.1 without build-id.
    Module libdrm.so.2 without build-id.
    Module kms.so without build-id.
    Module libXdmcp.so.6 without build-id.
    Module libXau.so.6 without build-id.
    Module libxcb-icccm.so.4 without build-id.
    Module libxcb.so.1 without build-id.
    Module xcb.so without build-id.
    Module libz.so.1 without build-id.
    Module libgcc_s.so.1 without build-id.
    Module libstdc++.so.6 without build-id.
    Module libassimp.so.5 without build-id.
    Module libvulkan.so.1 without build-id.
    Module vkmark without build-id.
    Stack trace of thread 23454:
    #0  0x0000fffc09476fe8 _ZN15KMSWindowSystemC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIc>
    #1  0x0000fffc09474d98 vkmark_window_system_create (kms.so + 0x14d98)
    #2  0x00000000004adbb0 _ZN18WindowSystemLoader18load_window_systemEv (vkmark + 0xadbb0)
    #3  0x0000000000407ff4 main (vkmark + 0x7ff4)
    #4  0x0000fffc096b6294 __libc_start_call_main (libc.so.6 + 0x26294)
    #5  0x0000fffc096b6368 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x26368)
    #6  0x00000000004087f0 _start (vkmark + 0x87f0)
    ELF object binary architecture: AARCH64

```
This is the latest commit from the master branch of vkmark, specifically https://github.com/vkmark/vkmark/commit/ab6e6f34077722d5ae33f6bd40b18ef9c0e99a15 .   I am running vkmark by launching it from Konsole on plasma6.

My custom kernel config is attached.
[broken-kernel-config.txt](https://github.com/user-attachments/files/18191789/broken-kernel-config.txt)

**Comment by zzywysm** [comment]
I didn't want to update my world to linux-asahi 6.12.x until I had tracked this down, so my investigation was all done on 6.11.8.

**Comment by hoshinolina** [comment]
This is a vkmark bug. It tries to probe the kms driver first, which opens `/dev/dri/card0` unconditionally, expects it to be a display device, and segfaults when it isn't. Building the Asahi driver in makes the GPU device the first DRI device, which is why that matters. On Fedora it doesn't repro because that device never exists on typical boots, since it's the EFI framebuffer which gets removed after the real display device probes, so you end up with card1 (GPU) and card2 (display) only and the KMS backend always fails to probe. If you `sudo ln -s card1 /dev/dri/card0` on Fedora it crashes the same way.

Please report upstream to vkmark.

Workaround is  `vkmark --winsys wayland`.
