### ISSUE TITLE
Asahi Linux Error APFS Error

### ISSUE THREAD

**Issue by BardofSprites** [AsahiLinux/linux#51]
Im trying to install asahi on my 2020 Macbook air. It's not working as intended. 

Your APFS Container resize request is below the APFS-system-imposed minimal container size

[installer.log](https://github.com/AsahiLinux/linux/files/9485570/installer.log)

**Comment by c272** [comment]
Looking at your `installer.log`, this seems identical to [asahi-installer#116](https://github.com/AsahiLinux/asahi-installer/issues/116). You entered Expert Mode, in which you are expected to manually pick a reasonable partition size. In this mode, `min` does not function correctly.

Simply electing to use normal mode instead of expert should allow you to use `min` and install properly. (Also - this is the kernel  repository, for issues with the installer you should open issues in the [asahi-installer](https://github.com/AsahiLinux/asahi-installer) repo).
