### ISSUE TITLE
Is there any problem with m1 mac speakers?

### ISSUE THREAD

**Issue by ghost** [AsahiLinux/linux#59]
In my mac m1, I can't hear audio both headphones and without headphones.

Is that features is not supported for now or how can I fix that?

Please help!

**Comment by ghost** [comment]
Have the same Problem on my M1 air full upgraded … :( only over usb card and then I loose connection on every video.

Greetz X73RM

**Comment by ghost** [comment]
Are you fixed that or still getting error? Now, I found the solution :)

**Comment by ghost** [comment]
No i don’t know any fix , could you tell me or send a link if you have.

Best Regards

**Comment by ghost** [comment]
Open your Konsole,

1) Type `alsamixer` and press enter
2) You will see audio settings (you don't need to touch anythings)
3) press `control + F6` and choose your default speaker `Macbook Speakers` and press enter
4) To exist from that press `esc`
5) type in your konsole `sudo alsactl store` and press enter
6) reboot your mac

That solve my issue. You can read on freeCodecamp here - https://www.freecodecamp.org/news/how-to-fix-broken-audio-in-headphones-and-speakers-linux/

(In that post, it will tell to disable `auto-mute` but in AshiLinux there is no auto mute function)

**Comment by ghost** [comment]
Wow thanks so much does only the headphone work ? Now I can switch completely to Asahi : )

And God Bless the Programmers all best i wish 💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕

**Comment by ghost** [comment]
This worked for a few minutes after update now no more ^^ lol 😂

**Comment by ghost** [comment]
Yep! I also getting error.
It only work for headphone now (also shown in Asahi documentation). 

But don't worry, we can fix that later.

**Comment by ghost** [comment]
no problems it’s cool that it works anyways ^^ linux on that Chip it‘s ultra fast I can’t believe how the updates and installations running.

Cool 😎 we hear us‘ keep going.
Greetz from Germany 🇩🇪

**Comment by hphilm** [comment]
@x73rm5 and @stkhant there is a reason why the speakers are not yet enabled ... 

Speakers

Speakers are functioning, however remain unsafe. There is a serious risk of blowing up the speakers should you misconfigure any part of the userspace stack. As such, on machines where we have (preliminary) support for speakers, the speakers are disabled in the devicetree. In order to get functioning speakers, you must manually edit the devicetree to enable it and build a new m1n1 payload containing the modifications. As this is potentially dangerous and suitable only for well seasoned power users, no specific instructions are provided.

https://github.com/AsahiLinux/linux/issues/53

**Comment by ghost** [comment]
Ok Phillip danke das wusste ich schon‘ ich bin schon seit meiner Kindheit mit Linux beschäftigt aber riskieren will ich es trotzdem nicht meine Lautsprecher zu zerstören ^^ da geht dann auch ne externe usb karte jedoch bricht mir der Ton auch dort immer ab bei jedem 2ten YouTube Video das habe ich auf meinem Debian nie so gehabt. Naja wird schon. Peace ✌️

Ok Phillip thanks I already knew that' I've been busy with Linux since my childhood but I still don't want to risk destroying my speakers ^^ then an external USB card will also work, but the sound always breaks off for me there every 2nd YouTube video I never had that on my Debian. Well it will may some day. Peace ✌️
